/*
  Warnings:

  - You are about to drop the `Trasaction` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropForeignKey
ALTER TABLE "Trasaction" DROP CONSTRAINT "Trasaction_accountId_fkey";

-- DropTable
DROP TABLE "Trasaction";

-- CreateTable
CREATE TABLE "Transaction" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "amount" FLOAT8 NOT NULL,
    "ref" STRING,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "accountId" INT4 NOT NULL,

    CONSTRAINT "Transaction_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
